name       : dolphin-plugins
version    : 22.04.1
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/dolphin-plugins-22.04.1.tar.xz : 81220b19a5224fe720a2c5755900519b29b625a89051fd9ce269d611b122b0ff
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
