name       : dolphin-plugins
version    : 20.08.3
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/dolphin-plugins-20.08.3.tar.xz : 0cb1b232c9b86811107ef9270ba2be42d242157b8daeeeffd1493ae635f0aa3a
homepage   : https://kde.org/applications/system/org.kde.dolphin-plugins
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - dolphin-devel
    - ktexteditor-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
