name       : dolphin-plugins
version    : 21.04.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/dolphin-plugins-21.04.0.tar.xz : 9fb395bfc62b726a4feae87b89d97294262cdadbeadf69706d7f314b1ff488d2
homepage   : https://kde.org/applications/system/org.kde.dolphin-plugins
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
