name       : dolphin-plugins
version    : 21.12.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/dolphin-plugins-21.12.0.tar.xz : f2bc5b9874e36376afc3bcdaaa558ae7277cea724597353026dd403c2a741394
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
