name       : dolphin-plugins
version    : 21.12.1
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/dolphin-plugins-21.12.1.tar.xz : 7ca1acc82ae1fb1909b1f98797a1a6f5d74ad78cc969f96cb65bb7e5f7062279
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
