name       : dolphin-plugins
version    : 21.04.3
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/dolphin-plugins-21.04.3.tar.xz : 9239c300cb7b27bb7810cedce11132bf9b0e4e0bcc1c1aba94b9cb8092d51d44
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
