name       : dolphin-plugins
version    : 21.04.2
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/dolphin-plugins-21.04.2.tar.xz : 9654ad7175fcaa93dbf0003f5e63c948ac53982be9f7f54482a8774c53abc4b1
homepage   : https://kde.org/applications/system/org.kde.dolphin-plugins
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
