name       : dolphin-plugins
version    : 20.12.3
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/dolphin-plugins-20.12.3.tar.xz : fcb2ca9acf2ef3b7aaa8d5bf66920fc79983952cda7223416d172802ad9a5e80
homepage   : https://kde.org/applications/system/org.kde.dolphin-plugins
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
