name       : dolphin-plugins
version    : 23.04.2
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/dolphin-plugins-23.04.2.tar.xz : bcd1e0b49744e3ff8dceb604beec25792f8bcca1ed47ae19c16c10c7bb755ddf
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
