name       : dolphin-plugins
version    : 21.08.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/dolphin-plugins-21.08.2.tar.xz : c72a2ba9fb2199092c8806a9819b3c5706d983db7f763f1962b8933655bde808
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
