name       : dolphin-plugins
version    : 19.04.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/dolphin-plugins-19.04.0.tar.xz : c2898e0a64d5a9eab2a4bd661694b75805adfd0a925f1a21f894892264f96469
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
builddeps  :
    - pkgconfig(Qt5Core)
    - dolphin-devel
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
