name       : dolphin-plugins
version    : 23.04.1
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/dolphin-plugins-23.04.1.tar.xz : 5922605d28d0bcda37caafcbcb6d4edf866c4d4911ec6c7c513cc12ed03cddb5
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
