name       : dolphin-plugins
version    : 20.04.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/dolphin-plugins-20.04.0.tar.xz : e38dc682d6b01f9e2403b5d98064b5c1b4f9c3bab9690084f6df252d5d1a127a
homepage   : https://kde.org/applications/system/org.kde.dolphin-plugins
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - dolphin-devel
    - ktexteditor-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
