name       : dolphin-plugins
version    : 21.04.1
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/dolphin-plugins-21.04.1.tar.xz : cfe900f5c3d34205e60175636e18c1f7982d4029d31e58ff788392235051461c
homepage   : https://kde.org/applications/system/org.kde.dolphin-plugins
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
