name       : dolphin-plugins
version    : 22.04.3
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/dolphin-plugins-22.04.3.tar.xz : 2e4a2cc09caa82689b724295d5514b30f06d0f9c7fc594f3635d31217eee21c6
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
