name       : dolphin-plugins
version    : 18.04.1
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/dolphin-plugins-18.04.1.tar.xz : cc5dd1c6b31b09b4972c0372304857fd75bed8a00448afb6300dc08ebcbf5f01
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - dolphin-devel
    - extra-cmake-modules
    - kdelibs4support-devel
    - ki18n-devel
    - kio-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
