name       : dolphin-plugins
version    : 22.04.2
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/dolphin-plugins-22.04.2.tar.xz : ae6a5e36efb53b9f88ebcecdad78d73660d661f285dea135ccf337d1adf8ef28
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
