name       : dolphin-plugins
version    : 23.04.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/dolphin-plugins-23.04.0.tar.xz : 68a4d8129c6740c487c77a8bd1025e1a3a75646d9a3303b44551d9fccfaed0d6
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
