name       : dolphin-plugins
version    : 21.08.3
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/dolphin-plugins-21.08.3.tar.xz : 17686354ee0396567464902babbaf77985cec103d7cc0b0c8a25c5dffc171125
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
