name       : dolphin-plugins
version    : 22.04.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/dolphin-plugins-22.04.0.tar.xz : 1cd12901c8dfe7220e7b5e445ddcbb1cdc375d1379560054e9dce6201c828150
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
