name       : dolphin-plugins
version    : 17.12.3
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/dolphin-plugins-17.12.3.tar.xz : 8e31695ea1ddfd58b35059d5389e5b9b401fd10294d50765a834ae81a8e6bb2d
license    : GPL-2.0
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - dolphin-devel
    - extra-cmake-modules
    - kdelibs4support-devel
    - ki18n-devel
    - kio-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
