name       : dolphin-plugins
version    : 21.08.1
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/dolphin-plugins-21.08.1.tar.xz : 39234026a703e7a1275950334ce31b924571ea27b1d538eeb3b2014fc7c9d53e
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
