name       : dolphin-plugins
version    : 19.08.1
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/dolphin-plugins-19.08.1.tar.xz : ce2452d9f878dfcff45739ff9eb4a3bde69c449c36182dee6b768f362e75ae2e
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
builddeps  :
    - pkgconfig(Qt5Core)
    - dolphin-devel
    - extra-cmake-modules
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
