name       : dolphin-plugins
version    : 22.08.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/dolphin-plugins-22.08.3.tar.xz : 703c4666d5fb9a48cca01b52ca5bc4aacbcba3a82c1656487f40334513851517
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
