name       : dolphin-plugins
version    : 21.12.3
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/dolphin-plugins-21.12.3.tar.xz : 65b5aa7fcc6b1d07499596a220ab54f0eeff2e60b2079f4180e13094b8337f65
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
