name       : dolphin-plugins
version    : 21.08.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/dolphin-plugins-21.08.0.tar.xz : 082e39843d6b9e06bb495617ad19e161e78a272600a1ea0fdfaefc77fbd220b4
homepage   : https://apps.kde.org/dolphin_plugins/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
optimize   : lto
builddeps  :
    - dolphin-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
