name       : dolphin-plugins
version    : 18.08.3
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/dolphin-plugins-18.08.3.tar.xz : 8324e4552d896970c90f9c63f202979b6520f18f291f4fa8b9baf33c25105e42
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Plugins for Dolphin
description: |
    Bazaar, dropbox, git, hg and svn plugins for dolphin.
builddeps  :
    - pkgconfig(Qt5Core)
    - dolphin-devel
    - extra-cmake-modules
    - kdelibs4support-devel
    - ki18n-devel
    - kio-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
